import type { Trivia } from '../types'

// Wrong answers for each card, so it can also be played as multiple choice.
const WRONG: Record<string, string[]> = {
  "Paul McCartney": ["John Lennon", "George Harrison", "Ringo Starr"],
  "Don't Stop": ["Go Your Own Way", "Dreams", "The Chain"],
  "Hipgnosis (Storm Thorgerson)": ["Andy Warhol", "Roger Dean", "Peter Blake"],
  "Quincy Jones": ["Nile Rodgers", "Rick Rubin", "Babyface"],
  "Bill Evans": ["Herbie Hancock", "Red Garland", "Thelonious Monk"],
  "A dollar bill on a fishhook": ["A rubber duck", "A goldfish", "A vinyl record"],
  "Goats": ["Horses", "Dogs", "Penguins"],
  "Stairway to Heaven": ["Black Dog", "Rock and Roll", "When the Levee Breaks"],
  "A motorcycle": ["A white horse", "A convertible", "A bicycle"],
  "Clarence Clemons": ["Steven Van Zandt", "Max Weinberg", "Patti Scialfa"],
  "Smashing his bass": ["Jumping off a speaker", "Lighting a guitar on fire", "Diving into the crowd"],
  "The Appalachian dulcimer": ["The banjo", "The ukulele", "The harmonica"],
  "Brian Johnson": ["Dave Evans", "Axl Rose", "Ian Gillan"],
  "The Mac's SimpleText (Fred)": ["Stephen Hawking", "Siri", "A BBC newsreader"],
  "Andy Warhol": ["Lou Reed", "Roy Lichtenstein", "Keith Haring"],
  "Joe Walsh": ["Don Felder", "Timothy B. Schmit", "Bernie Leadon"],
  "His brother Frankie": ["His father", "His wife Anna", "Tammi Terrell"],
  "Her cat, Telemachus": ["Her dog, Sam", "A guitar", "A stack of records"],
  "Robert Williams": ["H.R. Giger", "Frank Frazetta", "Raymond Pettibon"],
  "Ladysmith Black Mambazo": ["Soweto Gospel Choir", "The Mahotella Queens", "Los Lobos"],
  "Where the Streets Have No Name": ["With or Without You", "I Still Haven't Found What I'm Looking For", "Bullet the Blue Sky"],
  "Heddon Street": ["Carnaby Street", "Abbey Road", "Denmark Street"],
  "Happy": ["Tumbling Dice", "Rocks Off", "Sweet Virginia"],
  "Jack White": ["Jimmy Page", "Dave Grohl", "Josh Homme"],
  "Alright": ["King Kunta", "i", "These Walls"],
  "Pharrell Williams": ["Julian Casablancas", "Todd Edwards", "Panda Bear"],
  "Isn't She Lovely": ["Sir Duke", "I Wish", "As"],
  "Max Martin": ["Jack Antonoff", "Ryan Tedder", "Mark Ronson"],
}

const card = (
  album: string,
  artist: string,
  year: number,
  fact: string,
  question: string,
  answer: string,
): Trivia => ({ album, artist, year, fact, question, answer, wrong: WRONG[answer], source: 'deck' })

export const DECK: Trivia[] = [
  card('Abbey Road', 'The Beatles', 1969,
    'The cover was shot in about ten minutes outside EMI Studios on 8 August 1969.',
    'Which Beatle is barefoot on the Abbey Road cover?', 'Paul McCartney'),
  card('Rumours', 'Fleetwood Mac', 1977,
    'Recorded while both couples in the band were breaking up.',
    'Which Rumours song became a 1992 presidential campaign theme?', "Don't Stop"),
  card('The Dark Side of the Moon', 'Pink Floyd', 1973,
    'It spent over 900 weeks on the Billboard 200 album chart.',
    'Who designed the prism cover?', 'Hipgnosis (Storm Thorgerson)'),
  card('Thriller', 'Michael Jackson', 1982,
    'It is widely cited as the best-selling album of all time.',
    'Who produced Thriller?', 'Quincy Jones'),
  card('Kind of Blue', 'Miles Davis', 1959,
    'Most of it was recorded in first takes, from sketches the players saw that day.',
    'Which pianist plays on every track but "Freddie Freeloader"?', 'Bill Evans'),
  card('Nevermind', 'Nirvana', 1991,
    'It knocked Michael Jackson\'s Dangerous off #1 on the Billboard 200 in January 1992.',
    'What is the baby on the cover reaching for?', 'A dollar bill on a fishhook'),
  card('Pet Sounds', 'The Beach Boys', 1966,
    'Paul McCartney has called "God Only Knows" one of his favorite songs ever.',
    'What animals appear on the Pet Sounds cover?', 'Goats'),
  card('Led Zeppelin IV', 'Led Zeppelin', 1971,
    'The album has no official title; each member chose a symbol for the sleeve.',
    'Which 8-minute song closes side one?', 'Stairway to Heaven'),
  card('Purple Rain', 'Prince and the Revolution', 1984,
    'The title track\'s basic recording was captured live at First Avenue in Minneapolis.',
    'What kind of vehicle is Prince riding on the cover?', 'A motorcycle'),
  card('Born to Run', 'Bruce Springsteen', 1975,
    'Springsteen spent around six months recording the title track alone.',
    'Who is Bruce leaning on in the cover photo?', 'Clarence Clemons'),
  card('London Calling', 'The Clash', 1979,
    'Its pink-and-green lettering copies Elvis Presley\'s 1956 debut album.',
    'What is Paul Simonon doing on the cover?', 'Smashing his bass'),
  card('Blue', 'Joni Mitchell', 1971,
    'She wrote much of it after travels in Europe, including a stay in Matala, Crete.',
    'Which instrument, new to her, is all over Blue?', 'The Appalachian dulcimer'),
  card('Back in Black', 'AC/DC', 1980,
    'Released five months after Bon Scott died; the all-black cover is a tribute.',
    'Who replaced Bon Scott on vocals?', 'Brian Johnson'),
  card('OK Computer', 'Radiohead', 1997,
    'Much of it was recorded at St Catherine\'s Court, a mansion owned by Jane Seymour.',
    'Which robotic voice reads the lyrics of "Fitter Happier"?', "The Mac's SimpleText (Fred)"),
  card('The Velvet Underground & Nico', 'The Velvet Underground', 1967,
    'Early pressings let you peel the banana skin to reveal a pink banana.',
    'Who designed the banana cover?', 'Andy Warhol'),
  card('Hotel California', 'Eagles', 1976,
    'The cover photo is the Beverly Hills Hotel, shot at sunset.',
    'Which guitarist joined the Eagles for this album?', 'Joe Walsh'),
  card("What's Going On", 'Marvin Gaye', 1971,
    'Berry Gordy initially refused to release the title song, calling it too political.',
    "Which family member's Vietnam letters inspired the album?", 'His brother Frankie'),
  card('Tapestry', 'Carole King', 1971,
    'It won four Grammys including Album of the Year.',
    'What animal sits beside Carole on the cover?', 'Her cat, Telemachus'),
  card('Appetite for Destruction', "Guns N' Roses", 1987,
    'It is the best-selling debut album in US history.',
    'Which painter made the original (banned) cover art?', 'Robert Williams'),
  card('Graceland', 'Paul Simon', 1986,
    'Recorded largely with South African musicians, during the cultural boycott.',
    'Which vocal group sings on "Homeless"?', 'Ladysmith Black Mambazo'),
  card('The Joshua Tree', 'U2', 1987,
    'Named after the trees of the Mojave, photographed by Anton Corbijn.',
    'Which song opens the album?', 'Where the Streets Have No Name'),
  card('Ziggy Stardust', 'David Bowie', 1972,
    'Full title: The Rise and Fall of Ziggy Stardust and the Spiders from Mars.',
    'In which London street was the cover shot?', 'Heddon Street'),
  card('Exile on Main St.', 'The Rolling Stones', 1972,
    'Much of it was recorded in the basement of Nellcôte, a villa in the south of France.',
    'Which Exile song did Keith Richards sing lead on?', 'Happy'),
  card('Lemonade', 'Beyoncé', 2016,
    'Released alongside an hour-long film that premiered on HBO.',
    'Which rock icon is credited on "Don\'t Hurt Yourself"?', 'Jack White'),
  card('To Pimp a Butterfly', 'Kendrick Lamar', 2015,
    'It closes with an "interview" built from a 1994 Tupac recording.',
    'Which song became a Black Lives Matter anthem?', 'Alright'),
  card('Random Access Memories', 'Daft Punk', 2013,
    'They used live musicians, including Nile Rodgers and Giorgio Moroder.',
    'Which singer is featured on "Get Lucky"?', 'Pharrell Williams'),
  card('Songs in the Key of Life', 'Stevie Wonder', 1976,
    'Shipped as a double LP plus a bonus 7-inch EP.',
    'Which song celebrates his newborn daughter Aisha?', "Isn't She Lovely"),
  card('1989', 'Taylor Swift', 2014,
    'Her first album she called officially pop, named for her birth year.',
    'Which Swedish producer co-wrote "Shake It Off"?', 'Max Martin'),
]
