import type { Trivia } from '../types'

// Wrong answers for each card, so it can also be played as multiple choice.
const WRONG: Record<string, string[]> = {
  "Paul McCartney": ["John Lennon", "George Harrison", "Ringo Starr"],
  "Don't Stop": ["Go Your Own Way", "Dreams", "The Chain"],
  "Hipgnosis (Storm Thorgerson)": ["Andy Warhol", "Roger Dean", "Peter Blake"],
  "Quincy Jones": ["Nile Rodgers", "Rick Rubin", "Babyface"],
  "Bill Evans": ["Herbie Hancock", "Red Garland", "Thelonious Monk"],
  "A dollar bill on a fishhook": ["A rubber duck", "A goldfish", "A vinyl record"],
  "Goats": ["Horses", "Dogs", "Penguins"],
  "Stairway to Heaven": ["Black Dog", "Rock and Roll", "When the Levee Breaks"],
  "A motorcycle": ["A white horse", "A convertible", "A bicycle"],
  "Clarence Clemons": ["Steven Van Zandt", "Max Weinberg", "Patti Scialfa"],
  "Smashing his bass": ["Jumping off a speaker", "Lighting a guitar on fire", "Diving into the crowd"],
  "The Appalachian dulcimer": ["The banjo", "The ukulele", "The harmonica"],
  "Brian Johnson": ["Dave Evans", "Axl Rose", "Ian Gillan"],
  "The Mac's SimpleText (Fred)": ["Stephen Hawking", "Siri", "A BBC newsreader"],
  "Andy Warhol": ["Lou Reed", "Roy Lichtenstein", "Keith Haring"],
  "Joe Walsh": ["Don Felder", "Timothy B. Schmit", "Bernie Leadon"],
  "His brother Frankie": ["His father", "His wife Anna", "Tammi Terrell"],
  "Her cat, Telemachus": ["Her dog, Sam", "A guitar", "A stack of records"],
  "Robert Williams": ["H.R. Giger", "Frank Frazetta", "Raymond Pettibon"],
  "Ladysmith Black Mambazo": ["Soweto Gospel Choir", "The Mahotella Queens", "Los Lobos"],
  "Where the Streets Have No Name": ["With or Without You", "I Still Haven't Found What I'm Looking For", "Bullet the Blue Sky"],
  "Heddon Street": ["Carnaby Street", "Abbey Road", "Denmark Street"],
  "Happy": ["Tumbling Dice", "Rocks Off", "Sweet Virginia"],
  "Jack White": ["Jimmy Page", "Dave Grohl", "Josh Homme"],
  "Alright": ["King Kunta", "i", "These Walls"],
  "Pharrell Williams": ["Julian Casablancas", "Todd Edwards", "Panda Bear"],
  "Isn't She Lovely": ["Sir Duke", "I Wish", "As"],
  "Max Martin": ["Jack Antonoff", "Ryan Tedder", "Mark Ronson"],
  "Peter Blake": ["Andy Warhol", "Richard Hamilton", "Klaus Voormann"],
  "Tomorrow Never Knows": ["Eleanor Rigby", "Here, There and Everywhere", "Got to Get You into My Life"],
  "Like a Rolling Stone": ["Desolation Row", "Ballad of a Thin Man", "Tombstone Blues"],
  "London": ["Seattle", "New York", "Los Angeles"],
  "Art Garfunkel": ["Paul Simon", "Both, in harmony", "Roy Halee"],
  "Sid Vicious": ["Steve Jones", "Paul Cook", "Johnny Rotten"],
  "Martin Scorsese": ["John Landis", "Steven Spielberg", "David Fincher"],
  "Nile Rodgers": ["Quincy Jones", "Jellybean Benitez", "Stephen Bray"],
  "Every Breath You Take": ["Roxanne", "Message in a Bottle", "Don't Stand So Close to Me"],
  "Chris Cornell": ["Eddie Vedder", "Layne Staley", "Scott Weiland"],
  "Eddie Vedder": ["Chris Cornell", "Kurt Cobain", "Jerry Cantrell"],
  "Flea": ["Krist Novoselic", "Les Claypool", "Mike Mills"],
  "Fugees": ["TLC", "En Vogue", "Digable Planets"],
  "Queensbridge": ["Marcy", "Brownsville", "Lefrak City"],
  "Snoop Dogg": ["Ice Cube", "Eazy-E", "Warren G"],
  "Juicy": ["Big Poppa", "One More Chance", "Warning"],
  "Lower East Side": ["Harlem", "Greenwich Village", "Chelsea"],
  "Lovesong": ["Pictures of You", "Lullaby", "Just Like Heaven"],
  "Johnny Marr": ["Morrissey", "Andy Rourke", "Bernard Sumner"],
  "Peter Saville": ["Storm Thorgerson", "Neville Brody", "Vaughan Oliver"],
  "Once in a Lifetime": ["Burning Down the House", "Psycho Killer", "Road to Nowhere"],
  "Walter Becker and Donald Fagen": ["Hall and Oates", "Seals and Crofts", "Loggins and Messina"],
  "Running Up That Hill": ["Wuthering Heights", "Babooshka", "Cloudbusting"],
  "John Cale": ["Lou Reed", "Sterling Morrison", "Moe Tucker"],
  "McCoy Tyner": ["Herbie Hancock", "Thelonious Monk", "Red Garland"],
  "Folsom Prison Blues": ["I Walk the Line", "Ring of Fire", "A Boy Named Sue"],
  "The Dap-Kings": ["The Roots", "The Meters", "Booker T. & the M.G.'s"],
  "Rolling in the Deep": ["Someone Like You", "Set Fire to the Rain", "Rumour Has It"],
  "Todd Rundgren": ["Phil Spector", "Mutt Lange", "Jim Steinman"],
  "Mutt Lange": ["Todd Rundgren", "Bob Rock", "Rick Rubin"],
  "Battery": ["Master of Puppets", "Orion", "Welcome Home (Sanitarium)"],
  "Sting": ["Phil Collins", "Bono", "Peter Gabriel"],
}

const card = (
  album: string,
  artist: string,
  year: number,
  fact: string,
  question: string,
  answer: string,
): Trivia => ({ album, artist, year, fact, question, answer, wrong: WRONG[answer], source: 'deck' })

export const DECK: Trivia[] = [
  card('Abbey Road', 'The Beatles', 1969,
    'The cover was shot in about ten minutes outside EMI Studios on 8 August 1969.',
    'Which Beatle is barefoot on the Abbey Road cover?', 'Paul McCartney'),
  card('Rumours', 'Fleetwood Mac', 1977,
    'Recorded while both couples in the band were breaking up.',
    'Which Rumours song became a 1992 presidential campaign theme?', "Don't Stop"),
  card('The Dark Side of the Moon', 'Pink Floyd', 1973,
    'It spent over 900 weeks on the Billboard 200 album chart.',
    'Who designed the prism cover?', 'Hipgnosis (Storm Thorgerson)'),
  card('Thriller', 'Michael Jackson', 1982,
    'It is widely cited as the best-selling album of all time.',
    'Who produced Thriller?', 'Quincy Jones'),
  card('Kind of Blue', 'Miles Davis', 1959,
    'Most of it was recorded in first takes, from sketches the players saw that day.',
    'Which pianist plays on every track but "Freddie Freeloader"?', 'Bill Evans'),
  card('Nevermind', 'Nirvana', 1991,
    'It knocked Michael Jackson\'s Dangerous off #1 on the Billboard 200 in January 1992.',
    'What is the baby on the cover reaching for?', 'A dollar bill on a fishhook'),
  card('Pet Sounds', 'The Beach Boys', 1966,
    'Paul McCartney has called "God Only Knows" one of his favorite songs ever.',
    'What animals appear on the Pet Sounds cover?', 'Goats'),
  card('Led Zeppelin IV', 'Led Zeppelin', 1971,
    'The album has no official title; each member chose a symbol for the sleeve.',
    'Which 8-minute song closes side one?', 'Stairway to Heaven'),
  card('Purple Rain', 'Prince and the Revolution', 1984,
    'The title track\'s basic recording was captured live at First Avenue in Minneapolis.',
    'What kind of vehicle is Prince riding on the cover?', 'A motorcycle'),
  card('Born to Run', 'Bruce Springsteen', 1975,
    'Springsteen spent around six months recording the title track alone.',
    'Who is Bruce leaning on in the cover photo?', 'Clarence Clemons'),
  card('London Calling', 'The Clash', 1979,
    'Its pink-and-green lettering copies Elvis Presley\'s 1956 debut album.',
    'What is Paul Simonon doing on the cover?', 'Smashing his bass'),
  card('Blue', 'Joni Mitchell', 1971,
    'She wrote much of it after travels in Europe, including a stay in Matala, Crete.',
    'Which instrument, new to her, is all over Blue?', 'The Appalachian dulcimer'),
  card('Back in Black', 'AC/DC', 1980,
    'Released five months after Bon Scott died; the all-black cover is a tribute.',
    'Who replaced Bon Scott on vocals?', 'Brian Johnson'),
  card('OK Computer', 'Radiohead', 1997,
    'Much of it was recorded at St Catherine\'s Court, a mansion owned by Jane Seymour.',
    'Which robotic voice reads the lyrics of "Fitter Happier"?', "The Mac's SimpleText (Fred)"),
  card('The Velvet Underground & Nico', 'The Velvet Underground', 1967,
    'Early pressings let you peel the banana skin to reveal a pink banana.',
    'Who designed the banana cover?', 'Andy Warhol'),
  card('Hotel California', 'Eagles', 1976,
    'The cover photo is the Beverly Hills Hotel, shot at sunset.',
    'Which guitarist joined the Eagles for this album?', 'Joe Walsh'),
  card("What's Going On", 'Marvin Gaye', 1971,
    'Berry Gordy initially refused to release the title song, calling it too political.',
    "Which family member's Vietnam letters inspired the album?", 'His brother Frankie'),
  card('Tapestry', 'Carole King', 1971,
    'It won four Grammys including Album of the Year.',
    'What animal sits beside Carole on the cover?', 'Her cat, Telemachus'),
  card('Appetite for Destruction', "Guns N' Roses", 1987,
    'It is the best-selling debut album in US history.',
    'Which painter made the original (banned) cover art?', 'Robert Williams'),
  card('Graceland', 'Paul Simon', 1986,
    'Recorded largely with South African musicians, during the cultural boycott.',
    'Which vocal group sings on "Homeless"?', 'Ladysmith Black Mambazo'),
  card('The Joshua Tree', 'U2', 1987,
    'Named after the trees of the Mojave, photographed by Anton Corbijn.',
    'Which song opens the album?', 'Where the Streets Have No Name'),
  card('Ziggy Stardust', 'David Bowie', 1972,
    'Full title: The Rise and Fall of Ziggy Stardust and the Spiders from Mars.',
    'In which London street was the cover shot?', 'Heddon Street'),
  card('Exile on Main St.', 'The Rolling Stones', 1972,
    'Much of it was recorded in the basement of Nellcôte, a villa in the south of France.',
    'Which Exile song did Keith Richards sing lead on?', 'Happy'),
  card('Lemonade', 'Beyoncé', 2016,
    'Released alongside an hour-long film that premiered on HBO.',
    'Which rock icon is credited on "Don\'t Hurt Yourself"?', 'Jack White'),
  card('To Pimp a Butterfly', 'Kendrick Lamar', 2015,
    'It closes with an "interview" built from a 1994 Tupac recording.',
    'Which song became a Black Lives Matter anthem?', 'Alright'),
  card('Random Access Memories', 'Daft Punk', 2013,
    'They used live musicians, including Nile Rodgers and Giorgio Moroder.',
    'Which singer is featured on "Get Lucky"?', 'Pharrell Williams'),
  card('Songs in the Key of Life', 'Stevie Wonder', 1976,
    'Shipped as a double LP plus a bonus 7-inch EP.',
    'Which song celebrates his newborn daughter Aisha?', "Isn't She Lovely"),
  card('1989', 'Taylor Swift', 2014,
    'Her first album she called officially pop, named for her birth year.',
    'Which Swedish producer co-wrote "Shake It Off"?', 'Max Martin'),
  card("Sgt. Pepper's Lonely Hearts Club Band", "The Beatles", 1967,
    "The crowd on the cover was assembled from life-size cardboard cutouts.",
    "Who designed the cover with Jann Haworth?", "Peter Blake"),
  card("Revolver", "The Beatles", 1966,
    "Klaus Voormann, a friend from their Hamburg days, drew the cover.",
    "Which song closes Revolver?", "Tomorrow Never Knows"),
  card("Highway 61 Revisited", "Bob Dylan", 1965,
    "Al Kooper came to the session to play guitar and ended up playing the organ on the opener.",
    "Which song opens the album?", "Like a Rolling Stone"),
  card("Are You Experienced", "The Jimi Hendrix Experience", 1967,
    "The US edition added \"Purple Haze\", \"Hey Joe\" and \"The Wind Cries Mary\".",
    "In which city was the Experience formed?", "London"),
  card("Bridge over Troubled Water", "Simon & Garfunkel", 1970,
    "It was the duo's final studio album.",
    "Who sings lead on the title track?", "Art Garfunkel"),
  card("Never Mind the Bollocks, Here's the Sex Pistols", "Sex Pistols", 1977,
    "Its title led to an obscenity case in Nottingham, which the record shop won.",
    "Who replaced Glen Matlock on bass?", "Sid Vicious"),
  card("Bad", "Michael Jackson", 1987,
    "It was the first album with five consecutive Billboard Hot 100 number ones.",
    "Who directed the \"Bad\" short film?", "Martin Scorsese"),
  card("Like a Virgin", "Madonna", 1984,
    "The title track was written by Billy Steinberg and Tom Kelly.",
    "Who produced Like a Virgin?", "Nile Rodgers"),
  card("Synchronicity", "The Police", 1983,
    "It was the band's fifth and final studio album.",
    "Which song from it became their biggest hit?", "Every Breath You Take"),
  card("Superunknown", "Soundgarden", 1994,
    "It debuted at number one on the Billboard 200.",
    "Who was Soundgarden's singer?", "Chris Cornell"),
  card("Ten", "Pearl Jam", 1991,
    "It is named after basketball player Mookie Blaylock's jersey number.",
    "Who is Pearl Jam's singer?", "Eddie Vedder"),
  card("Jagged Little Pill", "Alanis Morissette", 1995,
    "She co-wrote and produced it with Glen Ballard.",
    "Which bassist plays on \"You Oughta Know\"?", "Flea"),
  card("The Miseducation of Lauryn Hill", "Lauryn Hill", 1998,
    "It won five Grammys, including Album of the Year.",
    "Which group was she in before going solo?", "Fugees"),
  card("Illmatic", "Nas", 1994,
    "The cover shows Nas as a child.",
    "In which New York housing project did Nas grow up?", "Queensbridge"),
  card("The Chronic", "Dr. Dre", 1992,
    "It was the first release on Death Row Records.",
    "Which rapper features heavily on it before his own debut?", "Snoop Dogg"),
  card("Ready to Die", "The Notorious B.I.G.", 1994,
    "It came out on Sean Combs' Bad Boy label.",
    "Which single samples Mtume's \"Juicy Fruit\"?", "Juicy"),
  card("Paul's Boutique", "Beastie Boys", 1989,
    "It was built from hundreds of samples with the Dust Brothers.",
    "The cover is a panorama of a street in which Manhattan neighborhood?", "Lower East Side"),
  card("Disintegration", "The Cure", 1989,
    "Robert Smith wrote much of it as he approached 30.",
    "Which single was a wedding present for Smith's wife Mary?", "Lovesong"),
  card("The Queen Is Dead", "The Smiths", 1986,
    "The cover star is the French actor Alain Delon.",
    "Who was the Smiths' guitarist?", "Johnny Marr"),
  card("Unknown Pleasures", "Joy Division", 1979,
    "The cover shows radio pulses from the pulsar CP 1919.",
    "Who designed the cover?", "Peter Saville"),
  card("Remain in Light", "Talking Heads", 1980,
    "Brian Eno produced it.",
    "Which song asks \"how did I get here?\"", "Once in a Lifetime"),
  card("Aja", "Steely Dan", 1977,
    "Wayne Shorter plays the saxophone solo on the title track.",
    "Who founded Steely Dan?", "Walter Becker and Donald Fagen"),
  card("Hounds of Love", "Kate Bush", 1985,
    "Side two is a song suite called \"The Ninth Wave\".",
    "Which song was a hit again in 2022 thanks to Stranger Things?", "Running Up That Hill"),
  card("Horses", "Patti Smith", 1975,
    "Robert Mapplethorpe shot the cover.",
    "Which Velvet Underground member produced it?", "John Cale"),
  card("A Love Supreme", "John Coltrane", 1965,
    "It was recorded in a single session in December 1964.",
    "Who plays piano on it?", "McCoy Tyner"),
  card("At Folsom Prison", "Johnny Cash", 1968,
    "It was recorded live at the California prison in January 1968.",
    "Which song had he written about the prison years earlier?", "Folsom Prison Blues"),
  card("Back to Black", "Amy Winehouse", 2006,
    "Mark Ronson and Salaam Remi produced it.",
    "Which band backs her on much of it?", "The Dap-Kings"),
  card("21", "Adele", 2011,
    "She named it after her age while writing it.",
    "Which song opens the album?", "Rolling in the Deep"),
  card("Bat Out of Hell", "Meat Loaf", 1977,
    "Jim Steinman wrote every song.",
    "Who produced it?", "Todd Rundgren"),
  card("Hysteria", "Def Leppard", 1987,
    "Drummer Rick Allen played with one arm after a 1984 car crash.",
    "Who produced it?", "Mutt Lange"),
  card("Master of Puppets", "Metallica", 1986,
    "It was the last album with bassist Cliff Burton.",
    "Which song opens the album?", "Battery"),
  card("Brothers in Arms", "Dire Straits", 1985,
    "It was one of the first albums to sell a million copies on CD.",
    "Who sings \"I want my MTV\" on \"Money for Nothing\"?", "Sting"),
]
